#!/usr/bin/env python3
"""Render the pipeline board and the greppable tracker from job/pipeline.json.

The direction used to run the other way: an HTML artifact was authored by hand and
markdown was extracted from it. That made the artifact a fourth copy of facts that
also lived in the context doc and the company folders, and it drifted the moment
anything changed — a declined company sat at "interviewing" for a week.

Now `pipeline.json` is the single place a stage is written, and both views are
generated. Editing `tracker.md` or `board.html` directly accomplishes nothing;
the next run overwrites them.

    python3 scripts/board.py [--check]

`--check` verifies the outputs are current without writing, for use in a hook.
Everything it touches is under job/, which is gitignored.
"""

import argparse
import html as html_mod
import json
import re
import sys
from datetime import date
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
JOB = REPO / "job"
DATA = JOB / "pipeline.json"
OUT_MD = JOB / "tracker.md"
OUT_HTML = JOB / "board.html"

# Stages that represent live work, rendered first and highlighted.
LIVE = {"interviewing", "waiting", "applied", "followup"}


def load() -> dict:
    return json.loads(DATA.read_text(encoding="utf-8"))


MONTHS = {m: i for i, m in enumerate(
    ["jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec"], 1)}
_DATE = (r"(?:(?P<mon>[A-Za-z]{3})[a-z]*\.? (?P<day>\d{1,2}),? (?P<year>\d{4})"
         r"|(?P<iso>\d{4}-\d{2}-\d{2}))")
APPLIED_STRONG = re.compile(r"\b(?:RE)?(?:APPLIED|Applied)\b[^.]{0,40}?" + _DATE)
APPLIED_WEAK = re.compile(r"\bapplied\b[^.]{0,40}?" + _DATE)


def _to_date(m: re.Match) -> date | None:
    try:
        if m.group("iso"):
            return date.fromisoformat(m.group("iso"))
        mon = MONTHS.get(m.group("mon").lower())
        return date(int(m.group("year")), mon, int(m.group("day"))) if mon else None
    except ValueError:
        return None


def applied_date(e: dict) -> date | None:
    """Read from the note's own 'APPLIED <date>' text - never guessed. Prefers the
    capitalized form sessions write when logging the event; takes the latest such
    date, since a reapplication is the one still pending. None if the note has none."""
    note = e.get("note", "")
    for pat in (APPLIED_STRONG, APPLIED_WEAK):
        found = [d for m in pat.finditer(note) if (d := _to_date(m))]
        if found:
            return max(found)
    return None


def next_action_date(e: dict) -> date | None:
    na = e.get("next_action")
    try:
        return date.fromisoformat(na["date"]) if isinstance(na, dict) else None
    except (KeyError, TypeError, ValueError):
        return None


def next_action_key(e: dict) -> tuple:
    """(undated, date, time) - optional "HH:MM" breaks ties within a day."""
    d = next_action_date(e)
    time = e["next_action"].get("time", "") if d else ""
    return (d is None, d or date.max, time)


def sort_rows(key: str, rows: list[dict]) -> list[dict]:
    """Applied: oldest application first. Considering and Interviewing: soonest
    next_action first. Undated entries go last, in their existing order
    (sorted() is stable)."""
    if key == "applied":
        return sorted(rows, key=lambda e: (applied_date(e) is None, applied_date(e) or date.max))
    if key in ("considering", "interviewing"):
        return sorted(rows, key=next_action_key)
    return rows


def card_date_line(key: str, e: dict) -> str:
    if key == "applied" and (d := applied_date(e)):
        return f"Applied {d.strftime('%b')} {d.day}, {d.year}"
    if key in ("considering", "interviewing") and (d := next_action_date(e)):
        na = e["next_action"]
        when = f"{d.strftime('%a %b')} {d.day}" + (f" {na['time']}" if na.get("time") else "")
        return f"Next: {when}" + (f" — {na['what']}" if na.get("what") else "")
    return ""


def grouped(data: dict) -> list[tuple[str, str, list[dict]]]:
    order = [s["key"] for s in data["stages"]]
    labels = {s["key"]: s["label"] for s in data["stages"]}
    by: dict[str, list[dict]] = {k: [] for k in order}
    for e in data["entries"]:
        by.setdefault(e.get("stage", "unknown"), []).append(e)
    keys = order + [k for k in by if k not in order]
    return [(k, labels.get(k, k), sort_rows(k, by[k])) for k in keys if by.get(k)]


def render_md(data: dict) -> str:
    lines = [
        "# Job search pipeline",
        "",
        "**Generated by `scripts/board.py` from `pipeline.json`. Do not edit — regenerate.**",
        "",
        f"{len(data['entries'])} entries · updated {data.get('updated', '?')}",
        "",
        " · ".join(f"{label} {len(rows)}" for _, label, rows in grouped(data)),
        "",
        "---",
        "",
    ]
    for key, label, rows in grouped(data):
        lines += [f"## {label} ({len(rows)})", ""]
        for e in rows:
            lines.append(f"### {e['company']} — {e['role'] or '?'}")
            lines.append("")
            if dl := card_date_line(key, e):
                lines += [f"**{dl}**", ""]
            if e.get("folder"):
                lines += [f"📁 **`job/{e['folder']}/`** — the source of truth for this company.", ""]
            if e.get("contacts"):
                lines += [f"**Contacts:** {e['contacts']}", ""]
            if e.get("note"):
                lines += [e["note"], ""]
        lines += ["---", ""]
    return "\n".join(lines)


def render_html(data: dict) -> str:
    cols = []
    for key, label, rows in grouped(data):
        cards = []
        for e in rows:
            note = e.get("note", "")
            short = html_mod.escape(note[:260] + ("…" if len(note) > 260 else ""))
            folder = (
                f'<p class="f">📁 job/{html_mod.escape(e["folder"])}/</p>'
                if e.get("folder") else ""
            )
            contacts = (
                f'<p class="c">{html_mod.escape(e["contacts"][:120])}'
                f'{"…" if len(e.get("contacts", "")) > 120 else ""}</p>'
                if e.get("contacts") else ""
            )
            dl = card_date_line(key, e)
            dline = f'<p class="d">{html_mod.escape(dl)}</p>' if dl else ""
            cards.append(
                f'<article class="card"><h3>{html_mod.escape(e["company"])}</h3>'
                f'<p class="r">{html_mod.escape(e["role"] or "—")}</p>'
                f"{dline}{folder}{contacts}"
                f'<p class="n">{short}</p></article>'
            )
        live = " live" if key in LIVE else ""
        cols.append(
            f'<section class="col{live}"><header><h2>{html_mod.escape(label)}</h2>'
            f'<span class="ct">{len(rows)}</span></header>{"".join(cards)}</section>'
        )

    total = len(data["entries"])
    live_n = sum(len(r) for k, _, r in grouped(data) if k in LIVE)
    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Job search pipeline</title>
<style>
  :root {{
    --bg:#F5F4F0; --surface:#fff; --ink:#14302E; --muted:#5C6B69;
    --rule:#D6D5CD; --acc:#0E6F68; --sig:#A8760A;
    --sans:system-ui,-apple-system,"Segoe UI",sans-serif;
    --mono:ui-monospace,SFMono-Regular,Menlo,monospace;
  }}
  @media (prefers-color-scheme:dark) {{
    :root {{ --bg:#0F1716; --surface:#16211F; --ink:#E7EDEB; --muted:#94A6A3;
             --rule:#27352F; --acc:#4FB5AA; --sig:#D9A227; }}
  }}
  *{{box-sizing:border-box}}
  body{{margin:0;padding:28px;background:var(--bg);color:var(--ink);font-family:var(--sans);
       font-size:14px;line-height:1.5}}
  h1{{font-size:1.5rem;letter-spacing:-.02em;margin:0 0 4px}}
  .meta{{font-family:var(--mono);font-size:.72rem;color:var(--muted);margin:0 0 24px}}
  .board{{display:flex;gap:16px;align-items:flex-start;overflow-x:auto;padding-bottom:20px}}
  .col{{flex:0 0 300px;min-width:300px}}
  .col > header{{display:flex;align-items:center;justify-content:space-between;gap:8px;
                 padding:0 0 8px;border-bottom:2px solid var(--rule);margin-bottom:10px}}
  .col.live > header{{border-bottom-color:var(--acc)}}
  .col h2{{font-size:.78rem;text-transform:uppercase;letter-spacing:.08em;margin:0;font-weight:700}}
  .col.live h2{{color:var(--acc)}}
  .ct{{font-family:var(--mono);font-size:.72rem;color:var(--muted)}}
  .card{{background:var(--surface);border:1px solid var(--rule);border-radius:3px;
         padding:11px 13px;margin-bottom:8px}}
  .col.live .card{{border-left:3px solid var(--acc)}}
  .card h3{{font-size:.92rem;margin:0 0 2px;letter-spacing:-.01em}}
  .r{{font-size:.8rem;color:var(--muted);margin:0 0 6px}}
  .d{{font-family:var(--mono);font-size:.7rem;color:var(--acc);margin:0 0 6px}}
  .f{{font-family:var(--mono);font-size:.68rem;color:var(--sig);margin:0 0 6px}}
  .c{{font-size:.72rem;color:var(--muted);margin:0 0 6px;padding-left:8px;
      border-left:2px solid var(--rule)}}
  .n{{font-size:.76rem;color:var(--muted);margin:0}}
</style></head><body>
<h1>Job search pipeline</h1>
<p class="meta">{total} entries · {live_n} live · updated {html_mod.escape(str(data.get("updated","?")))}
 · GENERATED from pipeline.json by scripts/board.py — do not edit</p>
<div class="board">{"".join(cols)}</div>
</body></html>
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="report whether outputs are current; write nothing")
    args = ap.parse_args()

    if not DATA.exists():
        print(f"no pipeline data at {DATA}", file=sys.stderr)
        return 1

    data = load()
    md, page = render_md(data), render_html(data)

    if args.check:
        stale = [
            p.name for p, want in ((OUT_MD, md), (OUT_HTML, page))
            if not p.exists() or p.read_text(encoding="utf-8") != want
        ]
        if stale:
            print("stale: " + ", ".join(stale))
            return 1
        print("current")
        return 0

    OUT_MD.write_text(md, encoding="utf-8")
    OUT_HTML.write_text(page, encoding="utf-8")
    counts = " · ".join(f"{label} {len(rows)}" for _, label, rows in grouped(data))
    print(f"{len(data['entries'])} entries -> {OUT_MD.name}, {OUT_HTML.name}")
    print(f"  {counts}")
    undated = [e["company"] for e in data["entries"]
               if e.get("stage") == "applied" and applied_date(e) is None]
    if undated:
        print(f"  no readable applied date, sorted last: {', '.join(undated)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
